# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AFN学习' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AFN学习
  pod 'AFNetworking', '~> 3.1.0'

end
